// Pre-computed optimal solution for the maze
// Generated by scripts/bruteforce.js
// Score: 162 | Time: 18.4s | Coins: 8/8

export const OPTIMAL_SOLUTION = {
  path: [
    { x: 8, y: 8 }, { x: 7, y: 8 }, { x: 6, y: 8 }, { x: 5, y: 8 },
    { x: 5, y: 7 }, { x: 4, y: 7 }, { x: 4, y: 6 }, { x: 4, y: 5 },
    { x: 3, y: 5 }, { x: 2, y: 5 }, { x: 1, y: 5 }, { x: 1, y: 4 },
    { x: 1, y: 3 }, { x: 2, y: 3 }, { x: 1, y: 3 }, { x: 1, y: 4 },
    { x: 1, y: 5 }, { x: 1, y: 6 }, { x: 1, y: 7 }, { x: 1, y: 8 },
    { x: 2, y: 8 }, { x: 3, y: 8 }, { x: 3, y: 7 }, { x: 4, y: 7 },
    { x: 5, y: 7 }, { x: 5, y: 6 }, { x: 6, y: 6 }, { x: 6, y: 5 },
    { x: 6, y: 4 }, { x: 7, y: 4 }, { x: 8, y: 4 }, { x: 8, y: 3 },
    { x: 8, y: 2 }, { x: 8, y: 1 }, { x: 8, y: 2 }, { x: 8, y: 3 },
    { x: 7, y: 3 }, { x: 6, y: 3 }, { x: 5, y: 3 }, { x: 4, y: 3 },
    { x: 4, y: 2 }, { x: 4, y: 1 }, { x: 5, y: 1 }, { x: 4, y: 1 },
    { x: 3, y: 1 }, { x: 2, y: 1 }, { x: 1, y: 1 }
  ],
  movements: [
    "LEFT", "LEFT", "LEFT", "UP", "LEFT", "UP", "UP", "LEFT",
    "LEFT", "LEFT", "UP", "UP", "RIGHT", "LEFT", "DOWN", "DOWN",
    "DOWN", "DOWN", "DOWN", "RIGHT", "RIGHT", "UP", "RIGHT", "RIGHT",
    "UP", "RIGHT", "UP", "UP", "RIGHT", "RIGHT", "UP", "UP",
    "UP", "DOWN", "DOWN", "LEFT", "LEFT", "LEFT", "LEFT", "UP",
    "UP", "RIGHT", "LEFT", "LEFT", "LEFT", "LEFT"
  ],
  score: 162,
  time: 18.4,
  coins: 8,
  distance: 46
}
